aws updates

diff --git a/script/aws_config_functions b/script/aws_config_functions
--- a/script/aws_config_functions
+++ b/script/aws_config_functions
@@ -10,102 +10,55 @@ aws_home_dir=~/.aws
 aws_local_config=$aws_home_dir/config
 aws_cred_file=$aws_home_dir/credentials
 blj_aws_config=$aws_home_dir/blj_config
-aws_args=
-
-
-# Return a prop stored in $blj_aws_config
-get_blj_prop() {
-	prop=$(cat $blj_aws_config | grep $1)
-	echo ${prop/$1=}
-}
-
-# Add a property to the current $blj_aws_config 
-# Param 1 Property name
-# Param 2 (optional) Property value
-add_aws_config() {
-	if [ $# -eq 1 ]; then
-		echo $1 >> $blj_aws_config 
-	elif [ $# -eq 2 ]; then
-		set_aws_config $1 $2
-		echo "$1=$2" >> $blj_aws_config 
-	fi
-}
-
-# MANUAL TESTING OVERRIDE VALUES
-aws_dev_config() {
-	set_aws_config dockerImgVer latest
-	set_aws_config ec2SpotPer 70
-	set_aws_config ec2Type SPOT
-	set_aws_config ec2Category t2.micro
-	set_aws_config myS3 blj-2019-03-25
-	set_aws_config stackName bljStack-2019-03-27
-}
+sheBang="#!/bin/bash"
 
 # Retrieve Linux AMI with name like amzn2-ami-ecs-hvm-2.0.20190301-x86_64-ebs AMI
 aws_get_ami() {
-	ami=$(aws ec2 describe-images --region $(aws_region) --owner amazon \
+	ami=$(aws ec2 describe-images --region $(get_blj_prop awsRegion) --owner amazon \
 		--filter "Name=name,Values=amzn2-ami-ecs-hvm-*$(date +%Y)*x86_64-ebs" \
 		--query "reverse(sort_by(Images, &CreationDate))[:1].ImageId" )
-	[ ${#ami} -eq 0 ] && echo "Error:  Unable to obtain AWS AMI template from region $(aws_region)" && exit 1
+	[ ${#ami} -eq 0 ] && echo "Error:  Unable to obtain AWS AMI template from region $(get_blj_prop awsRegion)" && exit 1
 	echo $ami
 }
 
-# Get an AWS property $1 from local AWS Config file $2 under the $(aws_profile) 
+# Get an AWS property $1 from local AWS Config file $2 under the awsProfile
 # Param 1 argName Parse filePath for a line that starts with argName
 # Param 2 filePath Target file
 aws_local_prop() {
+	[ ! -f "$2" ] && echo "Error:  File not found: $2" && return
 	foundProfile=0
 	prop="$1 = "
-	awsProfile=$(named_arg "$aws_args" awsProfile)
-	[ ${#awsProfile} -eq 0 ] && awsProfile="[default]"
-	#echo "Search config=$2 for arg=$1 in profile= $(named_arg "$aws_args" awsProfile)"
-	[ ! -f "$2" ] && echo "Error:  File not found: $2" && return
+	userProfile="[$(get_blj_prop awsProfile)]"
 	cat $2 | while read -r line; do
 		[ $foundProfile -eq 1 ] && [ "${line:0:1}" == "[" ] && break
 		[ $foundProfile -eq 1 ] && [ "${line:0:${#prop}}" == "$prop" ] && echo "${line/$prop}" && return
-		[ "$line" == "$awsProfile" ] && foundProfile=1
+		[ "$line" == "$userProfile" ] && foundProfile=1
 	done
-}
-
-# Return profile name, if used to return props, props specific to this profile are returned
-# Param 1 (optional) profile - name of existing profile, if null return [default] profile
-aws_profile() {
-	awsProfile=$(named_arg "$aws_args" awsProfile)
-	[ ${#awsProfile} -gt 0 ] && echo $awsProfile && return
-	[ $# -eq 0 ] && echo "[default]"
-	[ $# -gt 0 ] && echo "[$1]"
-}
-
-# Get the region defined in the AWS config file
-aws_region() {
-	region=$(named_arg "$aws_args" region)
-	[ ${#region} -eq 0 ] && region=$(aws_local_prop region $aws_local_config)
-	[ ${#region} -eq 0 ] && echo "Error:  Region undefined in $aws_local_config" && exit 1
-	echo $region
 }
 
 # Print AWS Config report
 aws_report_config() {
 	echo "AWS Config Report"
-	props=( "$aws_args" )
+	conf=$(cat $blj_aws_config)
+	[ ${#conf} -eq 0 ] && return
+	props=("$conf")
 	for arg in ${props[@]}; do
-		IFS2=$IFS && IFS="=" && tokens=( $arg )
+		IFS2=$IFS && IFS="=" && tokens=( ${arg} )
 		IFS=$IFS2 && echo "----> ${tokens[0]}=${tokens[1]}"
 	done
 }
 
-# Get a role get_role bljStack4 BatchServiceRoleArn 
-# Param 1 Stack name
-# Param 2 Role name
+# Get a role get_role for the configured stack 
+# Param 1 Role name
 aws_role() {
-	role=$(aws cloudformation describe-stacks --stack-name $1 --query "Stacks[*].Outputs[?OutputKey=='$2'].OutputValue")
+	role=$(aws cloudformation describe-stacks --stack-name $(get_blj_prop awsStack) --query "Stacks[*].Outputs[?OutputKey=='$1'].OutputValue")
 	[ ${#role} -eq 0 ] && return
 	echo $role
 }
 
 # Get the s3 bucket names in the user region
 aws_s3_buckets() {
-	myBuckets=$(aws s3api list-buckets --region $(aws_region) --query "Buckets[].Name")
+	myBuckets=$(aws s3api list-buckets --region $(get_blj_prop awsRegion) --query "Buckets[].Name")
 	[ ${#myBuckets} -eq 0 ] || [ "$myBuckets" == "None" ] && return
 	echo $myBuckets
 }
@@ -124,95 +77,82 @@ aws_stacks() {
 	echo $awsStacks
 }
 
-# Store Config properties
+# Get a prop stored in $blj_aws_config
+# Param 1 Prop name
+# Param 2 (optional) Default value
+get_blj_prop() {
+	prop=$(cat $blj_aws_config | grep $1)
+	val=${prop/$1=}
+	[ ${#val} -eq 0 ] && val=$2
+	exists=$(echo $prop | grep "$1=")
+	[ ${#exists} -gt 0 ] || [ ${#val} -gt 0 ] && response=$(set_blj_prop $1 $val)
+	echo $val
+}
+
+# Init AWS Config properties file: $blj_aws_config
+# Param 1 (optional) if true, use existing $blj_aws_config
 init_aws_config() {
-	set_aws_config awsProfile $(aws_profile)
-	set_aws_config dockerAccount $(named_arg "$@" docker.user)
-	set_aws_config dockerImgVer $(named_arg "$@" docker.imgVersion)
-	set_aws_config ec2SpotPer $(named_arg "$@" aws.ec2SpotPer)
-	set_aws_config ec2Type $(named_arg "$@" aws.ec2InstanceType)
-	set_aws_config ec2InstCategory $(named_arg "$@" aws.ec2InstanceCategory)
-	set_aws_config myS3 $(named_arg "$@" aws.s3)
-	set_aws_config stackName $(named_arg "$@" aws.stack)
-	set_aws_config region $(named_arg "$@" aws.region)
-	set_aws_config account_id $(aws ec2 describe-security-groups --group-names Default --query SecurityGroups[0].OwnerId)
-	
-	dockId=$(named_arg "$aws_args" dockerAccount)
-	dockerImgVer=$(named_arg "$aws_args" dockerImgVer)
-	[ ${#dockId} -eq 0 ] && set_aws_config dockerAccount $DOCKER_HUB_USER
-	[ ${#dockerImgVer} -eq 0 ] && set_aws_config dockerImgVer latest
-}
-
-# Remove AWS Config property
-# Param 1 - prop name 
-remove_aws_config() {
-	if [ ${#aws_args} -gt 0 ]; then
-		exists=$(echo $aws_args | grep -c "$1=")
-		if [ $exists -gt 0 ]; then
-			val=$(named_arg "$aws_args" $1) 
-			if [ ${#val} -gt 0 ]; then
-				aws_args="${aws_args/$1=$val}"
-			else
-				aws_args="${aws_args/$1=}"
-			fi
-		fi 
-	fi
-}
-
-# Move previous config to history folder and create a new config with current properties
-save_aws_config() {
 	[ ! -d $aws_home_dir/history ] && mkdir $aws_home_dir/history
-	[ -f $blj_aws_config ] && chmod -R 770 $blj_aws_config && mv $blj_aws_config $aws_home_dir/history/blj_config-$(date "+%Y-%m-%d.%H.%M.%S")
-	echo "# Config generated to run BioLockJ on the AWS cloud: $(date)" > $blj_aws_config
-	props=("$aws_args")
-	for arg in ${props[@]}; do
-		IFS2=$IFS && IFS="=" && tokens=( $arg )
-		IFS=$IFS2 && [ ${#tokens[*]} -eq 2 ] && echo "${tokens[0]}=${tokens[1]}" >> $blj_aws_config
-	done
-	echo "Saved blj Config to: $blj_aws_config"
-	aws_report_config
-}
-
-# Build account config (and create s3 bucket if needed)
-set_account_config() {
-	s3BucketName=$(named_arg "$aws_args" myS3)
-	stackName=$(named_arg "$aws_args" stackName)
-	set_aws_config access_id $(aws_local_prop aws_access_key_id $aws_cred_file)
-	set_aws_config key $(aws_local_prop aws_secret_access_key $aws_cred_file)
-	set_aws_config ami $(aws_get_ami)
-	set_aws_config s3Bucket $(get_s3 $s3BucketName)
-	set_aws_config stack $(get_stack_name $stackName)
-	set_aws_config region $(named_arg "$aws_args" $(aws_region))
-	remove_aws_config stackName
+	if [ -f $blj_aws_config ] && [ "$1" != "true" ]; then
+		mv $blj_aws_config $aws_home_dir/history/blj_config-$(date "+%Y-%m-%d.%H.%M.%S")
+	fi
+	[ $# -eq 0 ] && echo $sheBang > $blj_aws_config && chmod 770 $blj_aws_config
 	
+	x=$(get_blj_prop awsAccountId $(aws ec2 describe-security-groups --group-names Default --query SecurityGroups[0].OwnerId))
+	x=$(get_blj_prop awsEc2SpotPer 70)
+	x=$(get_blj_prop awsEc2AcquisitionStrategy SPOT)
+	x=$(get_blj_prop awsEc2InstanceType t2.micro)
+	x=$(get_blj_prop awsProfile default)
+	x=$(get_blj_prop awsRegion $(aws configure get region))
+	x=$(get_blj_prop dockerImgVersion latest)
+	x=$(get_blj_prop dockerUser biolockj)
+	
+	set_blj_prop access_id $(aws_local_prop aws_access_key_id $aws_cred_file)
+	set_blj_prop secret_key $(aws_local_prop aws_secret_access_key $aws_cred_file)
 }
 
-# Add a named arg to aws_args + return the new arg value
-# Param 1 - arg name
-# Param 2 - arg value
-set_aws_config() {
-	exists=$(echo $aws_args | grep -c "$1=${2/\[/\\\[}")
-	[ $exists -gt 0 ] && return
-	remove_aws_config $1
-	[ ${#aws_args} -gt 0 ] && aws_args="$aws_args $1=$2"
-	[ ${#aws_args} -eq 0 ] && aws_args="$1=$2"
-	echo "Set aws Config: $1=$2"
+# Remove AWS property - delete the line from the file
+# Param 1 - prop name 
+rm_blj_prop() {
+	TMP=~/.temp.txt
+	conf=$(cat $blj_aws_config)
+	[ ${#conf} -eq 0 ] && return
+	props=("$conf")
+	for arg in ${props[@]}; do
+		[ "$arg" == "$sheBang" ] && continue
+		IFS2=$IFS && IFS="=" && tokens=( ${arg} )
+		IFS=$IFS2 && [ "${tokens[0]}" != "$1" ] && echo ${arg} >> $TMP
+	done
+	rm $blj_aws_config
+	[ -f $TMP ] && mv $TMP $blj_aws_config
 }
 
-# Build stack config using stack and account_id references and build the roles
+# Set a prop stored in $blj_aws_config
+# Param 1 Prop name
+# Param 2 Prop value
+set_blj_prop() {
+	prop=$(cat $blj_aws_config | grep $1)
+	exists=$(echo $prop | grep "$1=${2/\[/\\\[}")
+	[ ${#exists} -gt 0 ] && return
+	rm_blj_prop $1
+	echo "$1=$2" >> $blj_aws_config
+	#echo "Set aws config:  $1=$2"
+}
+
+# Build stack config using awsStack and awsAccountId references and build the roles
 set_stack_config() {
-	stack=$(named_arg "$aws_args" stack)
-	account_id=$(named_arg "$aws_args" account_id)
-	set_aws_config keyName $stack-KeyPair
-	set_aws_config computeEnv $stack-ComputeEnv
-	set_aws_config queueName $stack-Queue
-	set_aws_config serviceRole $(aws_role $stack BatchServiceRoleArn)
-	set_aws_config iamFleetRole "arn:aws:iam::$account_id:role/$(aws_role $stack SpotIamFleetRoleArn)"
-	set_aws_config jobRoleArn $(aws_role $stack ECSTaskRole)
-	set_aws_config instanceRole "arn:aws:iam::$account_id:instance-profile/$(aws_role $stack IamInstanceProfileArn)"
-	set_aws_config bastionGroup $(aws_role $stack BastionSecurityGroup)
-	set_aws_config subnet $(aws_role $stack Subnet)
-	set_aws_config efsID $(aws_role $stack FileSystemId)
-	set_aws_config headNodeLaunchTemplate $(aws_role $stack HeadNodeLaunchTemplateId)
-	set_aws_config batchNodeLaunchTemplate $(aws_role $stack BatchNodeLaunchTemplateId)
+	awsStack=$(get_blj_prop awsStack)
+	awsAccountId=$(get_blj_prop awsAccountId)
+	set_blj_prop keyName $awsStack-KeyPair
+	set_blj_prop computeEnv $awsStack-ComputeEnv
+	set_blj_prop queueName $awsStack-Queue
+	set_blj_prop serviceRole $(aws_role BatchServiceRoleArn)
+	set_blj_prop iamFleetRole "arn:aws:iam::$awsAccountId:role/$(aws_role SpotIamFleetRoleArn)"
+	set_blj_prop jobRoleArn $(aws_role ECSTaskRole)
+	set_blj_prop instanceRole "arn:aws:iam::$awsAccountId:instance-profile/$(aws_role IamInstanceProfileArn)"
+	set_blj_prop bastionGroup $(aws_role BastionSecurityGroup)
+	set_blj_prop subnet $(aws_role Subnet)
+	set_blj_prop efsID $(aws_role FileSystemId)
+	set_blj_prop headNodeLaunchTemplate $(aws_role HeadNodeLaunchTemplateId)
+	set_blj_prop batchNodeLaunchTemplate $(aws_role BatchNodeLaunchTemplateId)
 }
diff --git a/script/aws_functions b/script/aws_functions
--- a/script/aws_functions
+++ b/script/aws_functions
@@ -26,7 +26,7 @@ build_compute_env() {
 # Build Docker Job defs to use with label references in Nextflow main.nf
 build_docker_job_defs() {
 	. $blj_aws_config
-	dockerModules=$(docker search $dockerAccount | grep -E ^$dockerAccount ) 
+	dockerModules=$(docker search $dockerUser | grep -E ^$dockerUser ) 
 	jobVcpus=2
 	jobRam=1024
 	IFS=$'\t'
@@ -34,7 +34,7 @@ build_docker_job_defs() {
 	echo $dockerModules | while read -r line; do
 		[ $(echo $line | grep -c blj_basic) -gt 0 ] && continue
 		module=$(echo $line | cut -f 1 -d " ")
-		jobImg="${module}:${dockerImgVer}"
+		jobImg="${module}:${dockerImgVersion}"
 		jobLabel=${jobImg/\//_} 
 		jobLabel=${jobLabel/:/_} 
 	    jobConfig="{ 
@@ -48,7 +48,7 @@ build_docker_job_defs() {
 			\"readonlyRootFilesystem\": false,
 			\"privileged\": true
 		}"
-		jobDef="${stack}_${jobLabel}"
+		jobDef="${awsStack}_${jobLabel}"
 		existingJob=$(aws batch describe-job-definitions --status ACTIVE --job-definition-name $jobDef --query "jobDefinitions[*].jobDefinitionName")
 		[ ${#existingJob} -gt 0 ] && echo "FOUND JOB: $existingJob" && continue
 		registeredJob=$(aws batch register-job-definition --job-definition-name $jobDef --type container --container-properties "${jobConfig}")
@@ -60,16 +60,16 @@ build_docker_job_defs() {
 
 # Build Cloud-formation Stack
 build_stack() {
-	stack=$(named_arg "$aws_args" stack)
-	[ $(is_stack_complete $stack) == "true" ] && echo "Found existing AWS Stack: $stack" && return 
-	echo "Building cloud formation stack: $stack. Please wait..."
+	awsStack=$(get_blj_prop awsStack)
+	[ $(is_stack_complete $awsStack) == "true" ] && echo "Found existing AWS Stack: $awsStack" && return 
+	echo "Building cloud formation stack: $awsStack. Please wait..."
 	stackYml="file://$BLJ/resources/aws/StackEFS.yml"
 	myIp=$(get_ip)/32
 	params='ParameterKey=NetworkAccessIP,ParameterValue='
-	aws cloudformation create-stack --template-body $stackYml --stack-name $stack --capabilities CAPABILITY_IAM --parameters ${params}${myIp}
+	aws cloudformation create-stack --template-body $stackYml --stack-name $awsStack --capabilities CAPABILITY_IAM --parameters ${params}${myIp}
 	numSecs=0
-	echo "Building Stack: $stack"
-	while [ $(is_stack_complete $stack) != "true" ]; do
+	echo "Building Stack: $awsStack"
+	while [ $(is_stack_complete $awsStack) != "true" ]; do
 		printf "." && sleep 5s && numSecs=$((numSecs+5))
 	done
 	echo "Secured to local IP: $myIp in $numSecs seconds"
@@ -77,7 +77,7 @@ build_stack() {
 
 # Build key pair + save to $aws_home_dir/$keyPair.pem file
 cache_key_pair() {
-	keyPair=$(named_arg "$aws_args" keyName)
+	keyPair=$(get_blj_prop keyName)
 	keyFile=$aws_home_dir/$keyPair.pem
 	if [ ! -f $keyFile ]; then
 		keys=$(aws ec2 describe-key-pairs)
@@ -122,19 +122,24 @@ get_ip() {
 # Param 1 (optional) S3 bucket name
 get_s3() {
 	s3Bucket=
-	if [ $# -eq 1 ]; then
-		s3Bucket=$(aws s3api list-buckets --region $(aws_region) --query "Buckets[?Name=='$1']|[*].Name")
+	myS3=$(get_blj_prop awsS3)
+	if [ ${#myS3} -gt 0 ]; then
+		s3Bucket=$(aws s3api list-buckets --region $(get_blj_prop awsRegion)  --query "Buckets[?Name=='$myS3']|[*].Name")
 		if [ ${#s3Bucket} -eq 0 ] || [ "$s3Bucket" == "None" ]; then
-			echo "Error:  S3 bucket [ aws.s3=$1 ] not found" && exit 1
+			echo "Error:  S3 bucket [ awsS3=$myS3 ] not found" && exit 1
 		fi
 	else
 		newS3=$(generate_name blj $(aws_s3_buckets))
-		s3Bucket=$(aws s3api create-bucket --region $(aws_region) --bucket $newS3)
+		s3Bucket=$(aws s3api create-bucket --region $(get_blj_prop awsRegion) --bucket $newS3)
 		if [ ${#s3Bucket} -eq 0 ] || [ "$s3Bucket" == "None" ]; then
 			echo "Error:  Failed to create S3 bucket: $newS3" && exit 1
 		fi
 	fi
 	echo $s3Bucket
+}
+
+get_s3_buckets() {
+	echo $(aws s3api list-buckets --region us-east-1 --query "Buckets[].Name")
 }
 
 # Return stack name.  If stack name arg given, verify is exists, else generate a new stack stack name.
@@ -145,7 +150,7 @@ get_stack_name() {
 		echo $(generate_name bljStack $awsStacks)
 	elif [ $# -eq 1 ]; then
 		awsStacks=$(aws_stacks CREATE_COMPLETE)
-		[ "${awsStacks/$1}" == "$awsStacks" ] && echo "Error:  Config property [ aws.stack=$1 ] does not exist!" && exit 1
+		[ "${awsStacks/$1}" == "$awsStacks" ] && echo "Error:  Config property [ awsStack=$1 ] does not exist!" && exit 1
 		echo $1
 	fi
 }
@@ -166,7 +171,7 @@ key_file() {
 }
 
 # Launch a new ec2 head node
-launch_head_node() {
+launch_ec2_head_node() {
 	. $blj_aws_config
 	runTime=0
 	instanceID=$(aws ec2 run-instances --count 1 --key-name $keyName --image-id $ami --security-group-ids $bastionGroup 
@@ -174,7 +179,6 @@ launch_head_node() {
 		--subnet-id $subnet --launch-template LaunchTemplateId=$headNodeLaunchTemplate --instance-type $ec2Category --query "Instances[].PrivateIpAddress" )
 
 	echo "Launching EC2 Instance: $instanceID"
-	# echo "https://console.aws.amazon.com/ec2/v2/home?region=$region#Instances:sort=instanceId"
 	systemStatus=starting
 	while [ "$systemStatus" != "ok" ]; do
 		systemStatus=$(aws ec2 describe-instance-status --instance-ids $instanceID --query "InstanceStatuses[*].SystemStatus.Status")
@@ -182,34 +186,48 @@ launch_head_node() {
 		sleep 10s
 		runTime=$((runTime+10))
 	done
-	echo " Instance:  $instanceID  created in $runTime seconds"
-	add_aws_config instanceID $instanceID
+	echo " Instance:  $instanceID created in $runTime seconds"
+	set_blj_config instanceID $instanceID
 	
-	add_aws_config privateHost $(aws ec2 describe-instances --instance-ids $instanceID --query "Reservations[*].Instances[*].PrivateDnsName")
-	add_aws_config privateIp $(aws ec2 describe-instances --instance-ids $instanceID --query "Reservations[].Instances[].PrivateIpAddress")
-	add_aws_config publicIp $(aws ec2 describe-instances --instance-ids $instanceID --query "Reservations[].Instances[].PublicIpAddress")
+	set_blj_config privateHost $(aws ec2 describe-instances --instance-ids $instanceID --query "Reservations[*].Instances[*].PrivateDnsName")
+	set_blj_config privateIp $(aws ec2 describe-instances --instance-ids $instanceID --query "Reservations[].Instances[].PrivateIpAddress")
+	set_blj_config publicIp $(aws ec2 describe-instances --instance-ids $instanceID --query "Reservations[].Instances[].PublicIpAddress")
 	
-	publicHost=$(add_aws_config publicHost $(aws ec2 describe-instances --instance-ids $instanceID --query "Reservations[].Instances[].PublicDnsName"))
+	publicHost=$(set_blj_config publicHost $(aws ec2 describe-instances --instance-ids $instanceID --query "Reservations[].Instances[].PublicDnsName"))
 
 	#remove previous hosts
-	keyFound=$(cat ~/.ssh/known_hosts | grep -c $publicHost)
-	[ $keyFound -gt 0 ] && ssh-keygen -f ~/.ssh/known_hosts -R $publicHost
+	keyFound=$(cat ~/.ssh/known_hosts | grep -c ${publicHost})
+	[ $keyFound -gt 0 ] && ssh-keygen -f ~/.ssh/known_hosts -R ${publicHost}
 
 	echo "Connecting directly via ssh:"
-	ssh -i $(key_file) ec2-user@$publicHost
+	ssh -i $(key_file) ec2-user@${publicHost}
 }
 
-# Main method, called to launch BioLockJ on AWS
-# Params format:  argName=argValue --> for example [ aws.s3=blj-2019-03-24 ]
-# Params (required) Config property: aws.ec2InstanceType, aws.ec2SpotPer, aws.profile, docker.imgVersion
-# Params (optional) Config properties that generate vals if undefined: aws.stack, aws.s3 
+# Main method, called to launch BioLockJ on AWS from localhost, if a Config is not given, defaults are used.
+# The optional file-path parameter can be passed to re-use existing objects on the cloud.
+# The parameter file should contain AWS configuration properties in the expected format.
+# Config file parameter format:  argName=argValue --> for example [ awsS3=blj-2019-03-24 ]
 run_aws() {
-	init_aws_config "$@" && aws_dev_config && set_account_config && build_stack && set_stack_config && \
-		save_aws_config && cache_key_pair && build_compute_env && add_aws_config $(build_docker_job_defs) && \
-		launch_ec2_head_node && echo "run_aws COMPLETE!"
+	init_aws_config true && set_account_config && build_stack && set_stack_config && cache_key_pair && \
+		build_compute_env && build_docker_job_defs && launch_ec2_head_node && echo "run_aws COMPLETE!"
+}
+
+# Build account config (and create s3 bucket if needed)
+set_account_config() {
+
+	set_blj_prop ami ami-007571470797b8ffa
+	set_blj_prop awsStack bljStack-2019-03-27-2
+	set_blj_prop awsS3 blj-2019-03-27-1
+	
+	stackName=$(get_blj_prop awsStack)
+	
+	x=$(get_blj_prop ami $(aws_get_ami))
+	x=$(get_blj_prop awsS3 $(get_s3))
+	x=$(get_blj_prop awsStack $(get_stack_name $stackName))
+	
 }
 
 # Upload data to the ec2 head node
-upload_to_head() {
+upload_to_head_node() {
 	ssh -i $(key_file) ec2-user@$(get_blj_prop publicHost)
 }
