refactor cleanup bug fix

diff --git a/script/biolockj b/script/biolockj
--- a/script/biolockj
+++ b/script/biolockj
@@ -15,16 +15,17 @@
 config=""
 params=""
 bljJar=$BLJ/dist/BioLockJ.jar
+restart=false
 
 [ ! -d "$BLJ_PROJ" ] && echo "Exit program - Required env variable BLJ_PROJ undefined" && exit 1
 [ ! -f "$bljJar" ] && echo "Exit program - $bljJar not found" && exit 1
 
 if [ $# -eq 1 ] && [ "$1" == "-h" ] || [ "$1" == "--help" ]; then   
     echo "BioLockJ $(get_version) - UNCC Fodor Lab July 2018"
-    echo "Run a new pipeline:                   biolockj <file>"
-    echo "Run a new pipeline:                   biolockj -c/--config <file>"
-    echo "Restart a failed pipeline:            biolockj -r/--restart <file>"
-    echo "Encrypt email password:                biolockj -p/--password <new_password> <file>"
+    echo "Run new pipeline:                     biolockj <file>"
+    echo "Run new pipeline:                     biolockj -c/--config <file>"
+    echo "Restart failed pipeline:              biolockj -r/--restart <directory/file>"
+    echo "Encrypt email password:               biolockj -p/--password <new_password> <file>"
     echo "View BioLockJ help menu:              biolockj -h/--help"
     exit 0
 elif [ $# -eq 1 ]; then
@@ -39,7 +40,8 @@ elif [ $# -eq 2 ]; then
 	if [ "$1" == "-c" ] || [ "$1" == "--config" ]; then
 		config=$2
 	elif [ "$1" == "-r" ] || [ "$1" == "--restart" ]; then
-		echo "Restarting pipeline..."
+		echo "Restart pipeline..."
+		restart=true
 		params=$1
 		config=$2
 	else
@@ -51,7 +53,8 @@ elif [ $# -eq 3 ]; then
 		params="$1 $2"   
 		config=$3
 	elif [ "$1" == "-r" ] || [ "$1" == "--restart" ] && [ "$2" == "-c" ] || [ "$2" == "--config" ]; then
-		echo "Restarting pipeline..."
+		echo "Restart pipeline..."
+		restart=true
 		params=$1
 		config=$3
 	else
@@ -61,7 +64,8 @@ else
     echo "Exit program - Invalid parameters: $@" && $BLJ/script/biolockj -h && exit 1 
 fi
 
-[ ! -f "$config" ] && echo "Exit program - $config not found"  && $BLJ/script/biolockj -h && exit 1
+$restart && [ ! -d "$config" ] && [ ! -f "$config" ] && echo "Exit program - $config is not a valid directory or file"  && $BLJ/script/biolockj -h && exit 1
+! $restart && [ ! -f "$config" ] && echo "Exit program - $config is not a valid file"  && $BLJ/script/biolockj -h && exit 1
 
 echo "BioLockJ JAR: $bljJar" 
 echo "BioLockJ Config:  $config"
