BioLockJ Release v1.0 (#103)
* AWS Support Ready
* Multi-threaded functionality added
* Bash env + Internal Config var references enabled
* Outstanding issue exists with Overriding default Docker DB with custom DBs.  Just found at build time - but am pushing code anyways so dev team can sync up.

diff --git a/script/biolockj b/script/biolockj
--- a/script/biolockj
+++ b/script/biolockj
@@ -10,126 +10,130 @@
 ##  BioLockJ Config file (2nd param) instead of running a pipeline      ##
 ##                                                                      ##
 ##########################################################################
-. $BLJ/script/blj_functions
+. "${AWS_LIB}"
 
-config=
-bljJar=$BLJ/dist/BioLockJ.jar
+bljJar=${BLJ}/dist/BioLockJ.jar
 
-# Convert input parameters to array with values "name,value"
+# Display BioLockJ release version
+display_version() {
+	if [ -f "${BLJ}/.version" ]; then
+		cat "${BLJ}/.version"
+	else
+		echo "Missing ${BLJ}/.version"
+	fi
+}
+
+# Show the help menu
+display_help() {
+    echo "BioLockJ $(display_version) - UNCC Fodor Lab July 2018"
+    echo "Run new pipeline:   biolockj                       <config_file>"
+    echo "Run new pipeline:             -c/--config/config   <config_file>"
+    echo "Run AWS pipeline:             -a/--aws/aws         <config_file>"
+    echo "Restart pipeline:             -r/--restart/restart  <directory>"
+    echo "Encrypt password:             -p/--pass/pass        <new_passw>"
+    echo "Use existing AWS env:         -e/--exist/exist"
+    echo "Show help menu:               -h/--help/help"
+    echo "Display BioLockJ version:     -v/--version/version"
+}
+
+# Convert input parameters to array with values "name=value"
 get_params() {
 	args=("$@")
 	numArgs=${#@}
 	i=0
-	found_config=false
-	name=
-    for arg in ${args[@]}
-    do  
-    		[ $((i%2)) -eq 0 ] && name=${arg}
-    		if [ $((i%2)) -eq 1 ]; then
-    			[ "$name" == "-c" ] || [ "$name" == "-config" ] && found_config=true
-    			echo "$name,${arg}"
+    for arg in ${args[@]}; do  
+		[ $((i%2)) -eq 0 ] && name=${arg//-} 
+		[ "$name" == "ea" ] || [ "$name" == "ae" ] && name="a" && echo "e=Y"
+		[ $((i%2)) -eq 0 ] && name=${name:0:1}
+		if [ $((i%2)) -eq 1 ]; then
+    			[ "$name" == "c" ] && myConfig=${arg}
+    			echo "$name=${arg}"
     			name=""
+    		elif [ "$name" == "e" ]; then
+    			echo "e=Y"
 		fi  
-    		i=$(expr $i + 1)
+    	i=$(expr $i + 1)
     done
-    [ ${#name} -gt 0 ] && [ ! found_config ] && echo "-c,$name"
+    [ ${#name} -gt 0 ] && [ ${#myConfig} -eq 0 ] && echo "c=$name"
 }
 
-# Get a named parameter from a "name,value" pair
-get_named_arg() {
-	args=("$@")
-	numArgs=${#@}
-	target=${args[$((numArgs-1))]}
-	args=${args[@]:0:$((numArgs-1))}
-	for arg in $args; 
-	do
-		IFS=","
-		tokens=( $arg )
-		[ ${#tokens[*]} -eq 2 ] && [ ${tokens[0]} == $target ] && echo ${tokens[1]} && return
-	done
+# Initialize script, read in script arguments
+init() {
+	inArray=$(get_params "$@")
+	runAws=$(named_arg $inArray a)
+	runExistingAws=$(named_arg $inArray e)
+	config=$(named_arg $inArray c)
+	restart=$(named_arg $inArray r)
+	newPass=$(named_arg $inArray p)
+	[ ${#config} -eq 0 ] && [ $# -eq 1 ] && config="${1}"
 }
 
-[ ! -d "$BLJ_PROJ" ] && echo "Exit program - Required env variable BLJ_PROJ undefined" && exit 1
-[ ! -f "$bljJar" ] && echo "Exit program - $bljJar not found" && exit 1
+# Launch AWS pipeline
+launchAwsPipeline() {
 
-if [ $# -eq 0 ]; then
-	echo "Exit program - Invalid parameters: $@" && $BLJ/script/biolockj -h && exit 1
-fi
+	run_aws "$runAws" start ${runExistingAws}
 
-if [ $# -eq 1 ] && [ "$1" == "-h" ] || [ "$1" == "--help" ]; then   
-    echo "BioLockJ $(get_version) - UNCC Fodor Lab July 2018"
-    echo "Run new pipeline:   biolockj               <config_file>"
-    echo "Run new pipeline:             -c/--config  <config_file>"
-    echo "Restart pipeline:             -r/--restart  <directory>"
-    echo "Encrypt password:             -p/--pass     <new_passw>"
-    echo "Show help menu:               -h/--help"
-    exit 0
-fi
+	if [ $? -eq 0 ]; then
+		exit_script "Successfully ran AWS Pipeline" 0
+	else
+		exit_script "Error [ biolockj ]: AWS Pipeline failed"
+	fi
+}
 
-inArray=$(get_params $@)
-
-config=$(get_named_arg $inArray -c)
-[ ${#config} -eq 0 ] && config=$(get_named_arg $inArray --config)
-
-restart=$(get_named_arg $inArray -r)
-[ ${#restart} -eq 0 ] && restart=$(get_named_arg $inArray --restart)
-
-newPass=$(get_named_arg $inArray -p)
-[ ${#newPass} -eq 0 ] && newPass=$(get_named_arg $inArray --password)
-
-
-if [ $# -eq 1 ] && [ ${#config} -eq 0 ]; then
-	config=$1
-fi
-
-if [ ${#newPass} -gt 0 ] && [ ${#config} -eq 0 ]; then
-	echo "Exit program - Invalid parameters: $@" && $BLJ/script/biolockj -h && exit 1 
-fi
-
-if [ ${#restart} -eq 0 ] && [ ${#config} -eq 0 ]; then
-	echo "Exit program - Invalid parameters: $@" && $BLJ/script/biolockj -h && exit 1 
-fi
-
-if [ ${#restart} -gt 0 ] && [ ! -d "$restart" ]; then
-	echo "Exit program - $restart is not a valid directory\n" && $BLJ/script/biolockj -h && exit 1
-fi 
-
-if [ ${#config} -gt 0 ] && [ ! -f "$config" ]; then
-	echo "Exit program - $config is not a valid file\n" && $BLJ/script/biolockj -h && exit 1
-fi
-
-if [ ${#newPass} -gt 0 ] && [ ${#config} -gt 0 ]; then
-	echo "Encrypt & save email password to Config property mail.encryptedPassword in $config\n"
-fi
-
-i=0
-initPipeline=$(most_recent_pipeline)
-pipelineDir=$(most_recent_pipeline)
-initJava=$(ps | grep -c java)
-numJava=$(ps | grep -c java)
-
-echo -e "Run Java Application with Command:  \"nohup java -jar $bljJar -b $BLJ_PROJ $@ >/dev/null 2>&1 &\""
-nohup java -jar $bljJar -b $BLJ_PROJ $@ >/dev/null 2>&1 &
-[ $? != 0 ] && echo "Exit program - Unable to run $bljJar" && exit 1
-echo "Initializing BioLockJ"
-
-while [ $i -lt 10 ] && [ "$initPipeline" == "$pipelineDir" ] && [ $initJava -eq $numJava ]; do
-	sleep 1
-	((i++))
-	pipelineDir="$(most_recent_pipeline)"
+# Launch local pipeline
+# Param 1 - array of script args "$@"
+launchLocalPipeline() {
+	i=0
+	initPipeline=$(most_recent_pipeline)
+	pipelineDir=$(most_recent_pipeline)
+	initJava=$(ps | grep -c java)
 	numJava=$(ps | grep -c java)
-done
+	
+	echo -e "Launching BioLockJ:  \"nohup java -jar $bljJar -b ${BLJ_PROJ} -u ${HOME} $@ >/dev/null 2>&1 &\""
+	nohup java -jar $bljJar -b "${BLJ_PROJ}" -u "${HOME}" $@ >/dev/null 2>&1 &
+	[ $? != 0 ] && ${BLJ}/script/biolockj -h && exit_script "Error [ biolockj ]:  Unable to run $bljJar"
+	printf "Initializing BioLockJ"
+	
+	while [ $i -lt 15 ] && [ "$initPipeline" == "$pipelineDir" ] && [ $initJava -eq $numJava ]; do
+		sleep 1 && ((i++)) && printf "." && pipelineDir="$(most_recent_pipeline)" && numJava=$(ps | grep -c java)
+	done
+	sleep 5
+	pipelineDir="$(most_recent_pipeline)"
+	echo "."
+	if [ ${#restart} -gt 0 ] && [ $numJava -gt $initJava ]; then
+		echo "Restarting pipeline:  $pipelineDir"
+	elif [ ${#restart} -eq 0 ] && [ "$initPipeline" != "$pipelineDir" ] || [ $numJava -gt $initJava ]; then
+		echo "Starting pipeline:  $pipelineDir"
+	elif [ ${#restart} -eq 0 ] ; then
+		exit_script "Error [ biolockj ]:  BioLockJ pipeline failed to start!" 1
+	fi
+	echo "blj_go       -> Move to pipeline output directory"
+	echo "blj_log      -> Tail pipeline log (accepts tail runtime parameters)"
+	echo "blj_summary  -> View module execution summary"
+}
 
-if [ ${#restart} -gt 0 ] && [ $numJava -gt $initJava ] && [ "$initPipeline" == "$pipelineDir" ]; then
-	echo "Restarted pipeline:  $pipelineDir"
-elif [ ${#restart} -eq 0 ] && [ "$initPipeline" != "$pipelineDir" ]; then
-	echo "Started new pipeline:  $pipelineDir"
-elif [ ${#restart} -eq 0 ]; then
-	echo "BioLockJ may have failed on: exec( \"nohup java -jar $bljJar -b $BLJ_PROJ $@ >/dev/null 2>&1 &\" )"
-	echo "Check $BLJ_PROJ for new pipeline directory"
-	exit 1
+# Verify input argument paths
+verifyArgPaths() {
+	[ ! -f "$runAws" ] && ${BLJ}/script/biolockj -h && exit_script "Error [ biolockj ]:  \"$config\" is not a valid file \n"
+}
+
+# Verify required local BioLockJ system paths exist
+verifyLocalBljPaths() {
+	[ ! -d "${BLJ_PROJ}" ] && exit_script "Error [ biolockj ]: Required env variable BLJ_PROJ undefined: \"${BLJ_PROJ}\""
+	[ ! -f "$bljJar" ] && exit_script "Error [ biolockj ]: Jar file \"$bljJar\" not found"
+} 
+
+if [ $# -eq 0 ] || [ "${1}" == "-h" ] || [ "${1}" == "--help" ] || [ "${1}" == "help" ]; then
+	display_help
+elif [ "${1}" == "-v" ] || [ "${1}" == "--version" ] || [ "${1}" == "version" ]; then
+	display_version
+else
+	init $@
+	if [ ${#runAws} -gt 0 ]; then
+		verifyArgPaths
+		launchAwsPipeline
+	else
+		verifyLocalBljPaths
+		launchLocalPipeline $@
+	fi
 fi
-
-echo "blj_go       -> Move to pipeline output directory"
-echo "blj_log      -> Tail pipeline log (accepts tail runtime parameters)"
-echo "blj_summary  -> View module execution summary"
diff --git a/script/blj_complete b/script/blj_complete
--- a/script/blj_complete
+++ b/script/blj_complete
@@ -2,25 +2,34 @@
 ###############################################################################
 ##                                                                           ##
 ##  This script manually completes current module and pipeline status.       ##
+##  All modules numbered below than the current module will also be reset.   ##
 ##                                                                           ##
 ###############################################################################
-. $BLJ/script/blj_functions
+. "${BLJ_LIB}"
 
-pipelineDir="$(dirname $PWD)"
+if [ ${#1} -gt 0 ]; then myDir="${1}"; else myDir="$PWD"; fi
+echo "Starting [ blj_complete ] to reset status of modules before/including $myDir to --> \"biolockjComplete\""
 
-if $(is_pipeline_dir $PWD); then
-	pipelineDir=$PWD
-elif ! $(is_pipeline_dir $pipelineDir); then 
-	echo "ABORT: blj_complete must be executed from a pipeline directory" && exit 1
+if $(is_pipeline_dir "$myDir"); then
+	pipeDir="$myDir" && myNum=$(($(ls "$pipeDir" | wc -l)+1))
+else
+	pipeDir=$(dirname "$myDir") && aDir=$(basename "$myDir") && myNum=$((10#${aDir%%_*}+1))
 fi
 
-echo "Update $pipelineDir status to: COMPLETE"
-[ ! -f "$pipelineDir/biolockjComplete" ] && touch "$pipelineDir/biolockjComplete" && echo "created $pipelineDir/biolockjComplete"
-[ -f "$pipelineDir/biolockjFailed" ] && rm "$pipelineDir/biolockjFailed" && echo "removed $pipelineDir/biolockjFailed"
+if ! $(is_pipeline_dir "$pipeDir"); then
+	exit_script "Error [ blj_reset ] target dir is not a pipeline or module root directory --> $myDir"
+fi
 
-for modDir in $pipelineDir/*; do
-	if $(is_module_dir "$modDir"); then
-		[ -f "$modDir/biolockjStarted" ] && rm "$modDir/biolockjStarted" && echo "deleted $modDir/biolockjStarted"
-		[ ! -f "$modDir/biolockjComplete" ] && touch "$modDir/biolockjComplete" && echo "created $modDir/biolockjComplete"
+[ -f "$pipeDir/biolockjComplete" ] && rm "$pipeDir/biolockjComplete" && echo "Deleted $pipeDir/biolockjComplete"
+[ -f "$pipeDir/biolockjFailed" ] && rm "$pipeDir/biolockjFailed" && echo "Deleted $pipeDir/biolockjFailed"
+found=false
+for modDir in $pipeDir/*; do
+	if ! $(is_empty "$modDir") && $(is_module_dir "$modDir"); then
+		dirName=$(basename "$modDir")
+		[ $((10#${dirName%%_*})) -lt $myNum ] && [ -f "$modDir/biolockjStarted" ] && found=true && \
+			rm "$modDir/biolockjStarted" && echo "Deleted $modDir/biolockjStarted" && \
+			[ ! -f "$modDir/biolockjComplete" ] && touch "$modDir/biolockjComplete" && echo "Created $modDir/biolockjComplete" 
 	fi
 done
+
+[ $found == false ] && echo "All pipeline directories up to/including $myDir already complete - no changes made"
diff --git a/script/blj_functions b/script/blj_functions
--- a/script/blj_functions
+++ b/script/blj_functions
@@ -4,6 +4,19 @@
 ##                                                               ##
 ###################################################################
 
+# Return value if found in input parameters
+# Param 1 - Script paramaters $@
+# Param 2 - Target param
+arg_exists() {
+	args=("$@")
+	numArgs=${#@}
+	target=${args[$((numArgs-1))]}
+	args=${args[@]:0:$((numArgs-1))}
+	for arg in $args; do
+		[ "$arg" == "$target" ] && echo "$target" && return
+	done
+}
+
 # Add a named arg to a space-delimited list of args (Use "=" to add a name-value pair)
 # Param 1 - arg name
 # Param 2 - arg value
@@ -16,16 +29,66 @@ add_named_arg() {
 	[ $# -eq 3 ] && echo "$myArgs $1=$2"
 }
 
+# Call ANT to build BioLockJ
+blj_build() {
+	echo "Building BioLockJ with ANT..."
+	[ ! -f "$BLJ/resources/build.xml" ] && exit_script "Error [ blj_build ]: ANT build script missing: $BLJ/resources/build.xml"
+	myDir=$PWD
+	cd $BLJ/resources
+	[ ${#1} -eq 0 ] && ant
+	[ ${#1} -gt 0 ] && ant $1
+	echo "Ant script execution complete"
+
+	if [ -f "$BLJ/dist/BioLockJ.jar" ]; then
+		ls -lh "$BLJ/dist/BioLockJ.jar"
+	else
+		echo "Build Failed - missing $BLJ/dist/BioLockJ.jar"
+	fi
+	cd $myDir
+}
+
+# Pull the latest Git code and build BioLockJ.jar
+blj_deploy() {
+	blj_sup_git
+	blj_git
+	blj_build build-jar
+}
+
+# Git latest $BLJ + build BioLockJ.jar
+blj_git() {
+	[ ! -d "${BLJ}" ] && echo "Cannot build BLJ: directory not found: ${BLJ}" && return
+	blj_git_reset "${BLJ}"
+}
+
+# Reset git repo + set file permissions 770
+# Param 1 Directory path of Git repo
+blj_git_reset() {
+	myDir=$PWD
+	echo "Get latest code from GitHub repo: $1"
+	cd $1
+	git fetch
+  	git checkout -q master
+  	git reset -q --hard origin/master  
+	chmod -R 770 $1
+	echo "==========================================================================="
+	echo "$1 Git pull SUCESSFULLY COMPLETED!"
+	chmod -R 770 $1
+	echo "$1 permissions set: 770"
+	echo "==========================================================================="
+	echo ""
+	cd $myDir
+}
+
 # This script navigates the $USER to their most recent pipeline and lists the current directory
 blj_go() {
-	[ ! -d "$BLJ_PROJ" ] && echo "Exit program - BLJ_PROJ: directory not found: $BLJ_PROJ" && return
+	[ ! -d "${BLJ_PROJ}" ] && echo "Exit program - BLJ_PROJ: directory not found: ${BLJ_PROJ}" && return
 	pipeline=$(most_recent_pipeline)
 	if [ ${#pipeline} -gt 0 ]; then
 		echo "Goto latest BioLockJ pipeline: $pipeline"
 		cd "$pipeline"
 		ls "$pipeline"
 	else
-		echo "No pipelines found in BLJ_PROJ: $BLJ_PROJ"
+		echo "No pipelines found in BLJ_PROJ: ${BLJ_PROJ}"
 	fi
 }
 
@@ -48,13 +111,14 @@ blj_log() {
 			\tail -1000 $pipeline/*.log 
 		fi
 	else
-		echo "No pipelines found in BLJ_PROJ: $BLJ_PROJ"
+		echo "No pipelines found in BLJ_PROJ: ${BLJ_PROJ}"
 	fi
 }
 
 # Rerun current pipeline from point of failure using same MASTER config
 blj_rerun() {
-	biolockj -r $PWD
+	echo "Restarting BioLockJ pipeline: $PWD"
+	if [ ${#1} -gt 0 ]; then biolockj -r $PWD -c "${1}"; else biolockj -r $PWD; fi
 }
 
 # This script prints the Summary BioModule output of current pipeline.
@@ -69,37 +133,58 @@ blj_summary() {
 		echo "Print summary file: $pipeline/$SUM"
 		cat "$pipeline/$SUM"
 	else
-		echo "No pipeline summary found in BLJ_PROJ: $BLJ_PROJ"
+		echo "No pipeline summary found in BLJ_PROJ: ${BLJ_PROJ}"
 	fi
+}
+
+# Git latest ${BLJ_SUP}
+blj_sup_git() {
+	[ ! -d "${BLJ_SUP}" ] && echo "Cannot build BLJ_SUP: directory not found: ${BLJ_SUP}" && return
+	blj_git_reset "${BLJ_SUP}"
 }
 
 # Return absolute path of current pipeline if in a pipeline directory
 current_pipeline() {
-	if [ -d "$BLJ_PROJ" ] && ! $(is_empty $BLJ_PROJ); then
+	if [ -d "${BLJ_PROJ}" ]; then
 		dir="$PWD"
 		parentDir="$(dirname $dir)"
-		while [ "$parentDir" != "$BLJ_PROJ" ] && [  "$parentDir" != "$(dirname $parentDir)" ] && ! $(is_pipeline_dir $dir)
+		while [ "$parentDir" != "${BLJ_PROJ}" ] && [ "$parentDir" != "$(dirname $parentDir)" ] && ! $(is_pipeline_dir $dir)
 		do
 			dir="$parentDir"
 			parentDir="$(dirname $parentDir)"
 		done
-		[ "$parentDir" == "$BLJ_PROJ" ] && echo $dir
+		[ "$parentDir" == "${BLJ_PROJ}" ] && echo $dir
    fi
 }
 
-# Return BioLockJ release version
-get_version() {
-	if [ -f "$BLJ/.version" ]; then
-		{ read -r v; } < "$BLJ/.version"
-		echo $v
-	else
-		echo "Missing $BLJ/.version"
-	fi
+# Check for a default profile in the $USER $HOME dir
+get_default_profile() {
+	user_profile="${HOME}"/.bash_profile
+	[ ! -f "${user_profile}" ] && user_profile="${HOME}"/.bashrc
+	[ ! -f "${user_profile}" ] && user_profile="${HOME}"/.profile
+	[ ! -f "${user_profile}" ] && user_profile="${HOME}"/.bash_login
+	[ ! -f "${user_profile}" ] && user_profile="${HOME}"/.zshenv
+	[ ! -f "${user_profile}" ] && user_profile="${HOME}"/.zprofile
+	[ ! -f "${user_profile}" ] && user_profile="${HOME}"/.zshrc
+	[ ! -f "${user_profile}" ] && user_profile="${HOME}"/.zlogin
+	[ -f "${user_profile}" ] && echo "${user_profile}"
 }
 
-# Return 0 if directory is empty (or missing)
+# Exit script after sleeping 10 seconds because in some cases (Docker bash shells) exit command will close the terminal window.
+# In this case, the user can at least view the message before the window closes.
+# Param 1 Exit message
+# Param 2 (optional) Numeric status code
+exit_script() {
+	status=$2
+	[ ${#status} -eq 0 ] && status=1
+	echo "$1" && sleep 15 && exit $2
+}
+
+# Check if parameter contains alpha-numeric chars [a-zA-Z0-9]
+# Param 1 - Any variable
 is_empty() {
-	[ ! -d "$1" ] || [ -z "$(\ls -A $1)" ]
+	x=$(echo "$1" | grep -c [a-zA-Z0-9])
+	[ ${x} -eq 0 ]
 }
 
 # Return TRUE if the directory path given ends with a valid module name
@@ -117,35 +202,47 @@ is_module_dir() {
 # Example: myTestPipeline_2019Jan01 returns TRUE
 is_pipeline_dir() {
 	dir=$1
-	[ ${dir: -1} == "/" ] && dir=${dir:0:$((${#dir}-1))}
+	[ "${dir: -1}" == "/" ] && dir=${dir:0:$((${#dir}-1))}
 	prefix=${dir: -10:1}
 	year=$(echo ${dir: -9:4} | egrep "^[0-9{4}]+$")
 	mon1=$(echo ${dir: -5:1} | egrep "^[A-S]+$")
 	mon23=$(echo ${dir: -4:2} | egrep "^[a-y{2}]+$")
 	day=$(echo ${dir: -2} | egrep "^[0-9{2}]+$")
-	[ -d "$1" ] && [ $prefix == "_" ] && [ ${#year} -eq 4 ] && [ ${#mon1} -eq 1 ] && [ ${#mon23} -eq 2 ] && [ ${#day} -eq 2 ]
+	[ "$dir" == "${dir/.}" ] && [ -d "$1" ] && [ "$prefix" == "_" ] && [ ${#year} -eq 4 ] && [ ${#mon1} -eq 1 ] && [ ${#mon23} -eq 2 ] && [ ${#day} -eq 2 ]
 }
 
-# Return absolute path of most recent pipeline
+# Kill running biolockj CMD
+# Param 1 - Override biolockj CMD name
+kill_blj() {
+	[ $# -eq 0 ] && procName="biolockj"
+	[ $# -gt 0 ] && procName="${1}"
+	pgrep ${procName}
+	pkill -9 [^]]${procName}
+}
+
+# Override function in $BLJ_SCRIPT/blj_functions to return the most recent pipeline dir-path 
 most_recent_pipeline() {
-	if [ -d "$BLJ_PROJ" ] && ! $(is_empty $BLJ_PROJ); then
-		for dir in $(ls -1dt $BLJ_PROJ/*); do
-			$(is_pipeline_dir $dir) && echo "$dir" && exit
+	IFS2="${IFS}"
+	if [ -d "${BLJ_PROJ}" ]; then
+		IFS=$'\n' && dirs=$(\ls -1dt ${BLJ_PROJ}/*) && myDirs=( "$dirs" )
+		for dir in $myDirs; do
+			$(is_pipeline_dir $dir) && IFS="${IFS2}" && echo "$dir" && return
 		done
 	fi
+	IFS="${IFS2}"
 }
 
 # Pass script input parameters + the argument name
 # Named arguments must be formated: "argName=argValue"
-# Param 1 aws_functions script args $@
-# Param 2 parameter name
+# Param 1 - Array of script args $@
+# Param 2 - Parameter name
 named_arg() {
 	args=("$@")
 	numArgs=${#@}
 	target=${args[$((numArgs-1))]}
 	args=${args[@]:0:$((numArgs-1))}
 	for arg in $args; do
-		IFS="=" && tokens=( $arg )
-		[ ${#tokens[*]} -eq 2 ] && [ ${tokens[0]} == $target ] && echo ${tokens[1]} && return
+		tokens=( ${arg//=/ } )
+		[ ${tokens[0]} == $target ] && echo ${tokens[1]} && return
 	done
 }
diff --git a/script/dockblj b/script/dockblj
--- a/script/dockblj
+++ b/script/dockblj
@@ -1,9 +1,9 @@
 #!/bin/bash
 ##################################################################################
 ##                                                                              ##
-##  Script launches BioLockJ in a Docker container                              ##
+##  Script launches BioLockJ via Docker + creates $DOCKER_CLONE_SCRIPT          ##
 ##                                                                              ##
-##  Bash env must include pipeline base directory: $BLJ_PROJ                    ##
+##  Bash env must include pipeline base directory: ${BLJ_PROJ}                  ##
 ##                                                                              ##
 ##  Required Parameters:                                                        ##
 ##  Config file path:       -c                                                  ##
@@ -17,122 +17,106 @@
 ##  Restart flag:           -r  <directory>                                     ##
 ##                                                                              ##
 ##################################################################################
-. $BLJ/script/blj_functions
+. "${DOCKER_LIB}"
 
-[ ! -d "$BLJ_PROJ" ] && echo "Exit program - Required bash variable BLJ_PROJ undefined" && exit 1
+cmd="dockblj ${@}"
+printf "\n---------> Execute CMD [  ${cmd}  ] \n\n"
 
-# Pass script input parameters + the argument value
-# Return value if found in input parameters
-arg_exists() {
-	args=("$@")
-	numArgs=${#@}
-	target=${args[$((numArgs-1))]}
-	args=${args[@]:0:$((numArgs-1))}
-	for arg in $args; do
-		[ "$arg" == "$target" ] && echo "$target" && return
-	done
-}
+[ ${#DOCKER_ID} -eq 0 ] && exit_script "Error [ dockblj ]: Required bash variable DOCKER_ID undefined"
+[ ! -d "${BLJ_PROJ}" ] && exit_script "Error [ dockblj ]: Required bash variable BLJ_PROJ undefined"
 
-# Populates the docker run BLJ_OPTIONS parameter
-# Include -docker to run BioLockJ in a Docker container
-# Include Docker container path to required Config file
-# Include all directory paths the Docker container may need to map volumes when spawning Docker compute nodes
+# Populate docker run env variable $BLJ_OPTIONS 
+# Always include vars to map Host paths: Config, $BLJ_PROJ, and $HOME.
+# In AWS mode, add -aws indicator, otherwise include the Host path for pipeline input. 
+# These paths are used by biolockj_controller to map Docker volumes for java_module containers
 blj_options() {
-	options="-docker -b $(blj_proj) -C $(dirname $config) -c /config/$(basename $config) -u $HOME" 
-	$(has_param $doRestart) && options="$options -r $(restart_dir)"
+	if $(has_param $runAws); then
+		options="-u ${EC2_HOME} -aws"
+	else
+		options="-u ${HOME}"
+	fi
+	$(has_param $doRestart) && options="$options -r ${BLJ_PROJ}/${doRestart#$(blj_proj)/}"
 	$(has_param $newPass) && options="$options -p $newPass"
 	$(has_param $inputDir) && options="$options -i $inputDir"
 	$(has_param $metaPath) && options="$options -m $metaPath"
-	$(has_param $HOST_BLJ) && options="$options -blj $HOST_BLJ"
-	$(has_param $HOST_BLJ_SUP) && options="$options -bljSup $HOST_BLJ_SUP"
-	echo $options
+	$(has_param $runDev) && $(has_param ${HOST_BLJ}) && options="$options -blj ${HOST_BLJ}"
+	$(has_param $runDev) && $(has_param ${HOST_BLJ_SUP}) && options="$options -bljSup ${HOST_BLJ_SUP}"
+	echo "$options -b $(blj_proj) -c $config"
 }
 
-# Return $HOST_BLJ_PROJ if called from within a docker container (such as blj_webapp), otherwise return $BLJ_PROJ
+# Return $HOST_BLJ_PROJ if called from within the biolockj_controller Docker container, otherwise return $BLJ_PROJ
+# If dir ends with "/" trim it off
 blj_proj() {
-	bljProj=$BLJ_PROJ
-	if $(has_param $inDocker); then
-		bljProj=$HOST_BLJ_PROJ
-		if $(has_param $bljProj); then
-			bljProj=$HOST_BLJ_PROJ
-		else
-			echo "Exit program - Required env variable HOST_BLJ_PROJ undefined" && exit 1
-		fi
-	fi
+	$(has_param $inDocker) && !$(has_param "${HOST_BLJ_PROJ}") && exit_script "Error [ dockblj ]: Required env variable HOST_BLJ_PROJ undefined"
+	if $(has_param $inDocker); then bljProj="${HOST_BLJ_PROJ}"; else bljProj="${BLJ_PROJ}"; fi
 	if [ "${bljProj: -1}" == "/" ]; then
 		len=$((${#bljProj}-1))
 		bljProj="${bljProj:0:len}"
 	fi
-	$(has_param $bljProj) && echo $bljProj && return
-	echo "Exit program - Required env variable BLJ_PROJ undefined" && exit 1
+	$(has_param $bljProj) && echo "${bljProj}" && return
+	exit_script "Error [ dockblj ]: Required env variable BLJ_PROJ undefined"
 }
 
-# Return boolean evaluation if single argument passed exists with a non-zero size
+# Build a script that can be used to launch a clone of the
+# Param 1 - Full Docker run command
+build_clone_script() {
+	echo "#!/bin/bash" > "${DOCKER_CLONE_SCRIPT}"
+	echo "# This script launches a clone of the last biolockj_controller (same env vars + volumes)" >> "${DOCKER_CLONE_SCRIPT}"
+	echo ${@/$(get_docker_img)/-ti $(dock_id)/biolockj_controller /bin/bash} >> "${DOCKER_CLONE_SCRIPT}"
+	chmod 777 "${DOCKER_CLONE_SCRIPT}"
+	echo "This script will execute a Docker clone of your most recent pipeline --> ${DOCKER_CLONE_SCRIPT}"
+	[ -f "${DOCKER_CLONE_SCRIPT}" ] && cat "${DOCKER_CLONE_SCRIPT}" & printf "\n"
+}
+
+# Get Docker image - add port, entrypoint, anc command if launching GUI
+get_docker_img() {
+	cmd=$(dock_id)/biolockj_controller	
+	$(has_param $launchGui) && cmd="-p 8080:3000 --expose 8080 -w '$BLJ/web_app' --entrypoint '/bin/bash' $cmd -c 'npm start'"
+	echo "${cmd}"
+}
+
+# Get mapped  Docker volumes
+get_volumes() {
+	if $(has_param $runAws); then
+		vols="-v ${DOCK_SOCK}:${DOCK_SOCK} -v ${EC2_HOME}:${EC2_HOME}:ro -v ${EFS}:${EFS}:delegated"
+	else
+		vols="-v ${DOCK_SOCK}:${DOCK_SOCK} -v $(blj_proj):${EFS_PROJ}:delegated"
+		if $(has_param $launchGui); then
+			vols="${vols} -v ${BLJ}/web_app/logs:/log:delegated -v ${BLJ}/resources/config/gui:${BLJ_CONFIG}"
+		else
+			vols="${vols} -v $inputDir:${BLJ_INPUT}:ro -v $(dirname $config):${BLJ_CONFIG}:ro"
+			$(has_param $metaPath) && vols="${vols} -v $metaPath:${BLJ_META}:ro"
+		fi
+	
+		$(has_param $runDev) && $(has_param ${HOST_BLJ}) && vols="${vols} -v ${HOST_BLJ}:/app/biolockj:ro"
+		$(has_param $runDev) && $(has_param ${HOST_BLJ_SUP}) && vols="${vols} -v ${HOST_BLJ_SUP}:/app/blj_support:ro"
+	fi
+	echo "${vols}"
+}
+
+# Boolean evaluation if single argument passed exists with a non-zero size
 has_param() {
 	[ ${#1} -gt 0 ]
 }
 
-# Get the Docker manager module (aws_manager or blj_manager) with $DOCKER_HUB_USER user prefix
-manager_type() {
-	if $(has_param $runAws); then
-		echo $DOCKER_HUB_USER/aws_manager
-	else
-		echo $DOCKER_HUB_USER/blj_manager
-	fi
-}
-
-# Get the internal Docker restart directory
-restart_dir() {
-	echo "/pipelines/${doRestart#$(blj_proj)/}"
-}
-
-# Call the docker run command with the correct parameters
-# If parameter is passed, add it to blj_options
+# Print and execute the docker run command with the correct volumes and env variables
 run_docker() {
-	D_SOCK="/var/run/docker.sock"
-	opt="$(blj_options)"
-	[ ${#1} -gt 0 ] && opt="$opt $1"
-	if $(has_param $metaPath); then
-		if $(has_param $HOST_BLJ) && $(has_param $HOST_BLJ_SUP); then
-			echo "execute[ docker run --rm -e 'BLJ_OPTIONS=$opt' -v $D_SOCK:$D_SOCK -v $inputDir:/input -v $metaPath:/meta -v $(blj_proj):/pipelines:delegated -v $(dirname $config):/config -v $HOST_BLJ:/app/biolockj -v $HOST_BLJ_SUP:/app/blj_support $(manager_type) ]"
-			docker run --rm -e "BLJ_OPTIONS=$opt" -v $D_SOCK:$D_SOCK -v $inputDir:/input -v $metaPath:/meta \
-				-v $(blj_proj):/pipelines:delegated -v $(dirname $config):/config -v $HOST_BLJ:/app/biolockj -v $HOST_BLJ_SUP:/app/blj_support $(manager_type)
-		elif $(has_param $HOST_BLJ); then
-			echo "execute[ docker run --rm -e 'BLJ_OPTIONS=$opt' -v $D_SOCK:$D_SOCK -v $inputDir:/input -v $metaPath:/meta -v $(blj_proj):/pipelines:delegated -v $(dirname $config):/config -v $HOST_BLJ:/app/biolockj $(manager_type) ]"
-			docker run --rm -e "BLJ_OPTIONS=$opt" -v $D_SOCK:$D_SOCK -v $inputDir:/input -v $metaPath:/meta \
-				-v $(blj_proj):/pipelines:delegated -v $(dirname $config):/config -v $HOST_BLJ:/app/biolockj $(manager_type)
-		else
-			echo "execute[ docker run --rm -e 'BLJ_OPTIONS=$opt' -v $D_SOCK:$D_SOCK -v $inputDir:/input -v $metaPath:/meta -v $(blj_proj):/pipelines:delegated -v $(dirname $config):/config $(manager_type)]"
-			docker run --rm -e "BLJ_OPTIONS=$opt" -v $D_SOCK:$D_SOCK -v $inputDir:/input -v $metaPath:/meta \
-				-v $(blj_proj):/pipelines:delegated -v $(dirname $config):/config $(manager_type)
-		fi
-	else
-		if $(has_param $HOST_BLJ) && $(has_param $HOST_BLJ_SUP); then
-			echo "execute[ docker run --rm -e 'BLJ_OPTIONS=$opt' -v $D_SOCK:$D_SOCK -v $inputDir:/input -v $(blj_proj):/pipelines:delegated -v $(dirname $config):/config -v $HOST_BLJ:/app/biolockj -v $HOST_BLJ_SUP:/app/blj_support $(manager_type) ]"
-			docker run --rm -e "BLJ_OPTIONS=$opt" -v $D_SOCK:$D_SOCK -v $inputDir:/input \
-				-v $(blj_proj):/pipelines:delegated -v $(dirname $config):/config -v $HOST_BLJ:/app/biolockj -v $HOST_BLJ_SUP:/app/blj_support $(manager_type)
-		elif $(has_param $HOST_BLJ); then
-			echo "execute[ docker run --rm -e 'BLJ_OPTIONS=$opt' -v $D_SOCK:$D_SOCK -v $inputDir:/input -v $(blj_proj):/pipelines:delegated -v $(dirname $config):/config -v $HOST_BLJ:/app/biolockj $(manager_type) ]"
-			docker run --rm -e "BLJ_OPTIONS=$opt" -v $D_SOCK:$D_SOCK -v $inputDir:/input \
-				-v $(blj_proj):/pipelines:delegated -v $(dirname $config):/config -v $HOST_BLJ:/app/biolockj $(manager_type)
-		else
-			echo "execute[ docker run --rm -e 'BLJ_OPTIONS=$opt' -v $D_SOCK:$D_SOCK -v $inputDir:/input -v $(blj_proj):/pipelines:delegated -v $(dirname $config):/config $(manager_type) ]"
-			docker run --rm -e "BLJ_OPTIONS=$opt" -v $D_SOCK:$D_SOCK -v $inputDir:/input \
-				-v $(blj_proj):/pipelines:delegated -v $(dirname $config):/config $(manager_type)
-		fi
-	fi
+	cmd="docker run --rm -e \"BLJ_OPTIONS=$(blj_options)\" $(get_volumes) $(get_docker_img)"
+	printf "\n---------> Execute CMD [  ${cmd}  ] \n\n"
+	build_clone_script "${cmd}"
+	docker run --rm -e "BLJ_OPTIONS=$(blj_options)" $(get_volumes) "$(get_docker_img)"
 }
 
 # Verify host directory exists, if dockblj is not deployed inside a Docker container
 verify_host_dir() {
 	#echo "validate Host Dir: $# + $1"
- 	[ $# -eq 2 ] && [ ${#1} -gt 0 ] && [ ! -d $1 ] && echo "Exit script - $2 directory not found: $1" && exit 1
+ 	[ $# -eq 2 ] && [ ! -d "${1}" ] && exit_script "Error [ dockblj ]: $2 directory not found: $1"
 }
 
 # Verify host file exists, if dockblj is not deployed inside a Docker container
 verify_host_file() {
 	#echo "validate Host Dir: $# + $1"
-	[ $# -eq 2 ] && [ ${#1} -gt 0 ] && [ ! -f $1 ] && echo "Exit script - $2 file not found: $1" && exit 1
+	[ $# -eq 2 ] && [ ! -f "${1}" ] && exit_script "Error [ dockblj ]: $2 file not found: $1"
 }
 
 # Verify paths are valid, if dockblj is not run inside a Docker container
@@ -140,31 +124,28 @@ verify_inputs() {
 	$(has_param $doRestart) && verify_host_dir $doRestart Restart
 	$(has_param $config) && verify_host_file $config Config
 	$(has_param $metaPath) && verify_host_dir $metaPath Metadata
-	! $(has_param $inputDir) && echo "Exit script. The -i parameter must reference a single input directory" && exit 1
-	IFS=","
-	dirPath=( $inputDir )
-	[ ${#dirPath[@]} -gt 1 ] && echo "Exit script. The -i parameter must reference a single input directory" && exit 1
+	! $(has_param $inputDir) && exit_script "Error [ dockblj ]: The -i parameter must reference a single input directory"
+	dirPath=( ${inputDir//, } )
+	[ ${#dirPath[@]} -gt 1 ] && exit_script "Error [ dockblj ]: The -i parameter must reference a single input directory"
 	verify_host_dir $dirPath Input
 }
 
-echo "Running dockblj..."
-runAws=$(named_arg "$@" -aws)
-config=$(named_arg "$@" -c)
 inDocker=$(arg_exists "$@" -docker)
+launchGui=$(arg_exists "$@" -gui)
+runAws=$(arg_exists "$@" -aws)
+runDev=$(arg_exists "$@" -dev)
+
+config=$(named_arg "$@" -c)
 inputDir=$(named_arg "$@" -i)
 metaPath=$(named_arg "$@" -m)
 newPass=$(named_arg "$@" -p)
 doRestart=$(named_arg "$@" -r)
+if ! $(has_param $inDocker); then
+	$(has_param "${BLJ_SUP}") && HOST_BLJ_SUP="${BLJ_SUP}" 
+	$(has_param $launchGui) && verify_inputs 
+fi
 
-! $(has_param $inDocker) && verify_inputs
+$(has_param $runDev) && echo "Run DEV mode!"
+$(has_param $runAws) && echo "Run AWS mode!"
 
 run_docker
-status=$?
-[ $status -ne 0 ] && echo "Exit script - Docker $(manager_type) pipeline failed" && exit $status
-
-if $(has_param $runAws); then
-	run_docker -aws
-	status=$?
-	[ $status -ne 0 ] && echo "Exit script - Docker $(manager_type) pipeline failed" && exit $status
-fi
-echo "Exit script - Docker $(manager_type) pipeline success!"
