updated script

diff --git a/script/blj_build b/script/blj_build
--- a/script/blj_build
+++ b/script/blj_build
@@ -30,7 +30,7 @@ if [ "$(valid_dir $BLJ/resources)" == "Y" ]; then
 	[ ${#1} -gt 0 ] && ant $1
 	echo "Ant script execution complete"
 else
-	echo "Invalid directory path: $BLJ/resources"
+	echo "Invalid directory path: $BLJ/resources" && exit 1
 fi
 
 if [ "$(valid_file $BLJ/dist/BioLockJ.jar)" == "Y" ]; then
diff --git a/script/blj_git b/script/blj_git
--- a/script/blj_git
+++ b/script/blj_git
@@ -20,11 +20,11 @@ echo "Pull latest BioLockJ code from GitHub"
 if [ "$(valid_dir $BLJ)" == "Y" ]; then
 	cd $BLJ
 	git pull
-	chmod -R 770 $BLJ
-	[ ${#BLJ_GRP_OWNER} -gt 0 ] && chown -R $BLJ_GRP_OWNER $BLJ
 	echo "Git pull Successful"
 else
-	echo "Invalid directory path: $BLJ"
+	echo "Invalid directory path: $BLJ" && exit 1
 fi
 
 blj_build standard-build
+chmod -R 770 $BLJ
+[ ${#BLJ_GRP_OWNER} -gt 0 ] && chown -R :$BLJ_GRP_OWNER $BLJ
