bug

diff --git a/script/blj_complete b/script/blj_complete
--- a/script/blj_complete
+++ b/script/blj_complete
@@ -6,21 +6,17 @@
 ###############################################################################
 . $BLJ/script/blj_functions
 
-parentDir="$(dirname $PWD)"
-currentDir="$(basename $PWD)"
+pipelineDir="$(dirname $PWD)"
 
-if $(is_pipeline_dir $currentDir); then
-	parentDir=$currentDir
-elif ! $(is_pipeline_dir $parentDir); then 
-	echo "ABORT: blj_complete must be executed from a pipeline module directory" && exit 1
+if $(is_pipeline_dir $PWD); then
+	pipelineDir=$PWD
+elif ! $(is_pipeline_dir $pipelineDir); then 
+	echo "ABORT: blj_complete must be executed from a pipeline directory" && exit 1
 fi
-
-pipelineDir=$(current_pipeline)
 
 echo "Update $pipelineDir status to: COMPLETE"
 [ ! -f "$pipelineDir/biolockjComplete" ] && touch "$pipelineDir/biolockjComplete" && echo "created $pipelineDir/biolockjComplete"
 [ -f "$pipelineDir/biolockjFailed" ] && rm "$pipelineDir/biolockjFailed" && echo "removed $pipelineDir/biolockjFailed"
-
 
 for modDir in $pipelineDir/*; do
 	if $(is_module_dir "$modDir"); then
