Docker + script updates (#26)

diff --git a/script/blj_build b/script/blj_build
--- a/script/blj_build
+++ b/script/blj_build
@@ -4,20 +4,18 @@
 ##  This script calls ant on build.xml to create BioLockJ.jar  ##
 ##                                                             ##
 #################################################################
-. $BLJ/script/blj_functions
 
 echo "Building BioLockJ with ANT..."
-if $(valid_dir $BLJ/resources); then
-	cd $BLJ/resources
-	[ ${#1} -eq 0 ] && ant
-	[ ${#1} -gt 0 ] && ant $1
-	echo "Ant script execution complete"
-else
-	echo "Invalid directory path: $BLJ/resources" && exit 1
-fi
+[ ! -f "$BLJ/resources/build.xml" ] && echo "ANT build script missing: $BLJ/resources/build.xml" && exit 1
 
-if $(valid_file $BLJ/dist/BioLockJ.jar); then
-	ls $BLJ/dist/BioLockJ.jar
+cd $BLJ/resources
+[ ${#1} -eq 0 ] && ant
+[ ${#1} -gt 0 ] && ant $1
+echo "Ant script execution complete"
+
+
+if [ -f "$BLJ/dist/BioLockJ.jar" ]; then
+	ls -lh "$BLJ/dist/BioLockJ.jar"
 else
 	echo "Build Failed - missing $BLJ/dist/BioLockJ.jar"
 fi
diff --git a/script/blj_reset b/script/blj_reset
--- a/script/blj_reset
+++ b/script/blj_reset
@@ -8,33 +8,24 @@
 . $BLJ/script/blj_functions
 
 parentDir="$(dirname $PWD)"
-currentDirName="$(basename $PWD)"
-maxNum=${currentDirName%_*}
+currentDir="$(basename $PWD)"
+targetNum=${currentDir%_*}
 
-modStarted=$PWD/biolockjStarted
-modComplete=$PWD/biolockjComplete
-pipelineComplete=$parentDir/biolockjComplete
+! $(is_pipeline_dir $parentDir) || (($targetNum < 0)) || [ ! -f "$PWD/biolockjComplete" ] && \
+	echo "ABORT: blj_reset must be executed within a biolockjComplete module directory" && exit 1
 
-if [ ${#maxNum} -ne 0 ] && $(valid_file $modComplete ); then
+echo "Reset $parentDir modules after and including step #$targetNum"
+[ -f "$parentDir/biolockjComplete" ] && rm "$parentDir/biolockjComplete" && echo "deleted $parentDir/biolockjComplete"
+[ ! -f "$PWD/biolockjStarted" ] && touch "$PWD/biolockjStarted" && echo "created $PWD/biolockjStarted"
+rm "$PWD/biolockjComplete" && echo "deleted $PWD/biolockjComplete"
 
-	echo "Reset BioLockJ pipeline $parentDir from step # $maxNum"
-	$(valid_file $pipelineComplete) && rm $pipelineComplete && echo "deleted $pipelineComplete"
-	$(valid_file $modStarted) && touch $modStarted && echo "created $modStarted"
-	rm $modComplete && echo "delete $modComplete"
-	
-	for pipelineDir in $parentDir/*; do
-		if $(valid_dir $pipelineDir); then
-			modStarted=$pipelineDir/biolockjStarted
-			modComplete=$pipelineDir/biolockjComplete
-			dir="$(basename $pipelineDir)"
-			modNum=${dir%_*}
-			if [ ${#modNum} -gt 0 ] && [ $modNum -gt $maxNum ]; then
-				$(valid_file $modComplete) && rm $modComplete && echo "delete $modComplete"
-				$(valid_file $modStarted) && touch $modStarted && echo "create $modStarted"
-			fi
+for modDir in $parentDir/*; do
+	if [ -d $modDir ]; then
+		dirName="$(basename $modDir)"
+		modNum=${dirName%_*}
+		if [ $modNum -gt $targetNum ] && ! $(is_empty $modDir); then
+			[ -f "$modDir/biolockjComplete" ] && rm "$modDir/biolockjComplete" && echo "deleted $modDir/biolockjComplete"
+			[ ! -f "$modDir/biolockjStarted" ] && touch "$modDir/biolockjStarted" && echo "created $modDir/biolockjStarted"
 		fi
-	done
-	
-else
-	echo "Command (blj_reset) aborted: no completed pipelines were found." 
-fi
+	fi
+done
diff --git a/script/dockblj b/script/dockblj
--- a/script/dockblj
+++ b/script/dockblj
@@ -4,69 +4,72 @@
 ##  Script launches BioLockJ in a Docker container                          ##
 ##                                                                          ##
 ##  Bash env must include pipeline base directory: $BLJ_PROJ                ##
-##  Must pass the script a minimum of 2 runtime parameters:                 ##
 ##                                                                          ##
-##  $config                Config file path                                 ##
-##  $inputDirPaths         Input dir paths (commma separated, no spaces)    ##
+##  Required Parameters                                                     ##
+##  Config file path:       config                                          ##
+##  Input directories:      inputDirPaths (commma separated, no spaces)     ##
 ##                                                                          ##
 ##  Optional parameters:                                                    ##
 ##                                                                          ##
-##  $metadataFilePath       Metadata file directory path                    ##
-##  $trimPrimersFilePath    Primer file directory path                      ##
-##  $BLJ_OPTIONS            Singleton options: -r or -p                     ##
+##  Admin email password    changePassword                                  ##
+##  Metadata directory:     metadataFilePath                                ##
+##  Primer directory:       trimPrimersFilePath                             ##
+##  Restart flag:           -r                                              ##
+##  Docker flag:            -docker                                         ##
 ##                                                                          ##
 ##############################################################################
-[ ${#BLJ} -gt 0 ] && [ -d "$BLJ" ] && . $BLJ/script/blj_functions
+. $BLJ/script/blj_functions
 
-! $(valid_dir $BLJ) && echo "Exit program - Required bash variable BLJ undefined" && exit 1
-! $(valid_dir $BLJ_PROJ) && echo "Exit program - Required bash variable BLJ_PROJ undefined" && exit 1
+[ ! -d "$BLJ_PROJ" ] && echo "Exit program - Required bash variable BLJ_PROJ undefined" && exit 1
 
 # Pass script input parameters + the argument value
+# Return value if found in input parameters
 arg_exists() {
 	args=("$@")
-	numArgs=${#args[@]-1}
-	lastIndex=$((numArgs-1))
-	target=${args[$lastIndex]}
-	args=${args[@]:0:${lastIndex-1}}
-	for arg in $args; do [ $arg == $target ] && echo $target && return; done
+	numArgs=${#@}
+	target=${args[$((numArgs-1))]}
+	args=${args[@]:0:$((numArgs-1))}
+	for arg in $args;
+	do
+		[ "$arg" == "$target" ] && echo "$target" && return
+	done
 }
 
 # Pass script input parameters + the argument name
-# Named argument must be formated like "argName=argValue"
+# Named arguments must be formated: "argName=argValue"
 get_named_arg() {
 	args=("$@")
-	numArgs=${#args[@]-1}
-	lastIndex=$((numArgs-1))
-	targetName=${args[$lastIndex]}
-	args=${args[@]:0:${lastIndex-1}}
-	for arg in $args; do
+	numArgs=${#@}
+	target=${args[$((numArgs-1))]}
+	args=${args[@]:0:$((numArgs-1))}
+	for arg in $args; 
+	do
 		IFS="="
-		#echo "checking $arg"
 		tokens=( $arg )
-		if [ ${#tokens[*]} -eq 2 ] && [ ${tokens[0]} == $targetName ]; then
+		if [ ${#tokens[*]} -eq 2 ] && [ ${tokens[0]} == $target ]; then
 			echo ${tokens[1]} && return
 		fi
 	done
-	echo ""
 }
+
 
 # Verify host file exists, if dockblj is not deployed inside a Docker container
 validateHostFile() {
 	#echo "validate Host Dir: $# + $1"
-	[ ! ${#inDockerContainer} -gt 0 ] && [ $# -eq 2 ] && ! $(valid_file $1) && echo "Exit script - $2 file not found: $1" && exit 1
+	[ ${#inDockerContainer} -eq 0 ] && [ $# -eq 2 ] && [ ! -f "$1" ] && echo "Exit script - $2 file not found: $1" && exit 1
 }
 
 # Verify host directory exists, if dockblj is not deployed inside a Docker container
 validateHostDir() {
 	#echo "validate Host Dir: $# + $1"
-	[ ! ${#inDockerContainer} -gt 0 ] && [ $# -eq 2 ] && ! $(valid_dir $1) && echo "Exit script - $2 directory not found: $1" && exit 1
+ 	[ ${#inDockerContainer} -eq 0 ] && [ $# -eq 2 ] && [ ! -d "$1" ] && echo "Exit script - $2 directory not found: $1" && exit 1
 }
 
 # Verify paths are valid, if dockblj is not deployed inside a Docker container
 validate_input() {
-	validateHostFile $config "Config"
-	validateHostDir $metadataFilePath "Metadata"
-	validateHostDir $trimPrimersFilePath "Primer"
+	validateHostFile $config Config
+	validateHostDir $metadataFilePath Metadata
+	validateHostDir $trimPrimersFilePath Primer
 	if [ ${#inputDirPaths} -lt 0 ]; then
 		echo "Exit script - Input directory is required" && exit 1
 	else
@@ -84,9 +87,8 @@ validate_input() {
 # Include all directory paths the manager may need to map volumes in spawned Docker compute node instances
 get_blj_options() {
 	options="-D -b $BLJ_PROJ" 
-	[ ${#changePassword} -gt 0 ] && options="$options $changePassword"
 	[ ${#restartPipeline} -gt 0 ] && options="$options $restartPipeline"
-	[ ${#inDockerContainer} -gt 0 ] && options="$options $inDockerContainer"
+	[ ${#changePassword} -gt 0 ] && options="$options -p $changePassword"
 	[ ${#config} -gt 0 ] && options="$options -C $(dirname $config) -c /config/$(basename $config)"
 	[ ${#inputDirPaths} -gt 0 ] && options="$options -i $inputDirPaths"
 	[ ${#metadataFilePath} -gt 0 ] && options="$options -m $metadataFilePath"
@@ -94,25 +96,37 @@ get_blj_options() {
 	echo $options
 }
 
-get_docker_volumes() {
-	VOL="-v /var/run/docker.sock:/var/run/docker.sock -v $BLJ_PROJ:/pipeline:delegated -v $(dirname $config):/config -v $inputDirPaths:/input"
-	[ ${#metadataFilePath} -gt 0 ] && VOL="$VOL -v $metadataFilePath:/meta"
-	[ ${#trimPrimersFilePath} -gt 0 ] && VOL="$VOL -v $trimPrimersFilePath:/primer"
-	echo $VOL
+# Print status message with GUI context and BLJ_OPTIONS
+get_status_msg() {
+	msg=""
+	if [ ${#inDockerContainer} -gt 0 ]; then
+		msg="Docker biolockj/webapp GUI"
+	else
+		msg="Host machine $BLJ/web_app GUI" 
+	fi
+	
+	if [ ${#restartPipeline} -gt 0 ]; then 
+		msg+=" restarting biolockj/manager Docker container"
+	else
+		msg+=" starting biolockj/manager Docker container"
+	fi
+	
+	echo "$msg with BLJ_OPTIONS=$(get_blj_options)"
 }
 
 config=$(get_named_arg "$@" "config")
 inputDirPaths=$(get_named_arg "$@" "inputDirPaths")
 metadataFilePath=$(get_named_arg "$@" "metadataFilePath")
 trimPrimersFilePath=$(get_named_arg "$@" "trimPrimersFilePath")
-changePassword=$(arg_exists "$@" "-p")
+changePassword=$(get_named_arg "$@" "-p")
 restartPipeline=$(arg_exists "$@" "-r")
 inDockerContainer=$(arg_exists "$@" "-docker")
-echo $inDockerContainer
+
+# Call function to verify input parameters are vaild
 validate_input
 
-options="$(get_blj_options)"
-echo "options: $options"
+# Call function to print status message
+echo $(get_status_msg)
 
 if [ ${#metadataFilePath} -gt 0 ] && [ ${#trimPrimersFilePath} -gt 0 ]; then
 	docker run -e "BLJ_OPTIONS=$(get_blj_options)" -v /var/run/docker.sock:/var/run/docker.sock \
