Release v0.9.5-beta bug fixes (#84)
* Fix Pipeline summary output + dockblj to properly report success

* Drop HumanN2 UNMAPPED and UNINTEGRATED columns by default

* remove blj_config printing $PATH, add dockblj -dev & hn2 props

* Updated some info logs to debug

* remove blj_config $PATH echo

* Fixed NullPointerException with Docker HOST_BLJ + HOST_BLJ_SUP env vars.

diff --git a/script/dockblj b/script/dockblj
--- a/script/dockblj
+++ b/script/dockblj
@@ -176,8 +176,9 @@ run_docker
 status=$?
 [ $status -ne 0 ] && echo "Exit script - Docker $(manager_type) pipeline failed" && exit $status
 
-$(has_param $runAws) && run_docker -aws
-status=$?
-[ $status -ne 0 ] && echo "Exit script - Docker $(manager_type) pipeline failed" && exit $status
-
+if $(has_param $runAws); then
+	run_docker -aws
+	status=$?
+	[ $status -ne 0 ] && echo "Exit script - Docker $(manager_type) pipeline failed" && exit $status
+fi
 echo "Exit script - Docker $(manager_type) pipeline success!"
