aws updates

diff --git a/script/make_nextflow b/script/make_nextflow
--- a/script/make_nextflow
+++ b/script/make_nextflow
@@ -15,7 +15,8 @@ bljVer="$(biolockj -v)"
 [${#bljVer} -eq 0] && bljVer="$($BLJ_SCRIPT/biolockj -v)"
 
 # Build the template
-# Param 1 - List of modules (using special delimiters)
+# Param 1 - template file path (output of function)
+# Param 2 - List of modules (using special delimiters)
 buildNexflowTemplate() {
 	echo "Building Nextflow Template...${1}"
 	modules="${2}"
@@ -37,6 +38,34 @@ buildNexflowTemplate() {
 		echo '    """' >> "${1}"
 		echo '}' >> "${1}"
 	done
+	addEndPipelineProcess "${1}" "${2}"
+	echo "-----------------------------------------------------------------------------------------"
+	[ -f "${1}" ] && echo "Success! -->  $summaryMsg" && echo "Deployed: ${1}" && cat "${1}" && \
+		echo "-----------------------------------------------------------------------------------------"	
+}
+
+# Add end pipeline process to the end of the template
+# Param 1 - template file path (output of function)
+addEndPipelineProcess() {
+	echo "addEndPipelineProcess()..."
+	echo "" >> "${1}"
+	echo "process end_biolockj_pipeline {" >> "${1}"
+	echo '    echo true' >> "${1}"
+	echo '    input:' >> "${1}"
+	echo '    val statusFile from Channel.watchPath( "BLJ_PIPELINE_DIR/biolockj*" )' >> "${1}"
+	echo '    """' >> "${1}"
+	echo '    #!/bin/bash' >> "${1}"
+	echo "    if [ $(basename $statusFile) == biolockjComplete ]; then" >> "${1}" 
+	echo "        echo 'EXIT NEXTFLOW - Pipeline Success'" >> "${1}"
+	echo "        exit 0" >> "${1}"
+	echo "    elif [ $(basename $statusFile) == biolockjFailed ]; then" >> "${1}"
+	echo "        clear_jobs" >> "${1}"
+	echo "        echo 'EXIT NEXTFLOW - Pipeline Failed'" >> "${1}"
+	echo "        exit 1" >> "${1}"
+	echo "    fi" >> "${1}"
+	echo '    """' >> "${1}"
+	echo '}' >> "${1}"
+
 	echo "-----------------------------------------------------------------------------------------"
 	[ -f "${1}" ] && echo "Success! -->  $summaryMsg" && echo "Deployed: ${1}" && cat "${1}" && \
 		echo "-----------------------------------------------------------------------------------------"	
@@ -53,18 +82,21 @@ get_modules() {
 # /user/ec2-user/.aws --> /root/.aws
 # /user/ec2-user/.nextflow/config --> /root/.nextflow/config
 stage_root_config() {
+	[ ! -f "${EC2_HOME}/.aws/credentials" ] && exit_script "Missing EC2-AWS config: ${EC2_HOME}/.aws/credentials"
+	[ ! -f "${EC2_HOME}/.nextflow/config" ] && exit_script "Missing EC2-Nextflow config: ${EC2_HOME}/.nextflow/config"
 	echo "Copy ${EC2_HOME}/.aws into ~"
 	cp -vr "${EC2_HOME}/.aws" ~ 
-	echo "Copy $(get_ec2_nextflow_dir)/config into ~/.nextflow"
-	cp -v "$(get_ec2_nextflow_dir)/config" ~/.nextflow
+	echo "Copy ${EC2_HOME}/.nextflow/config into ~/.nextflow"
+	cp -v "${EC2_HOME}/.nextflow/config" ~/.nextflow
+	#echo "Copy $(get_ec2_nextflow_dir)/config into ~/.nextflow"
+	#cp -v "$(get_ec2_nextflow_dir)/config" ~/.nextflow
 }
 
 if [ $# -lt 2 ]; then
 	echo "Missing [ make_nextflow ] args - 2 params required to build main.nf --->"
 	echo "  1) main.nf file-path"
 	echo "  2) List of modules formatted with specific delimiters"
-	sleep 15
-	exit 1
+	sleep 15 && exit 1
 else
 	stage_root_config
 	echo "Next - build template"
